### ISSUE TITLE
Tracking height and weight of children

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#214]
Special request of the social workers using:
App should get a new section to enter height and weight of children at a specific date, as this will be tracked regularly from this year onwards.

- [x] Create new Entity subtype
- [x] Add table of heigh-weight measures to the ChildDetailsComponent ("Health" section)
- [ ] Design a page for batch entry of measures for a group of children, similar to "add a month's attendance". (Maybe this should be generalized to use a generic component for both attendance and heigh-weight entry?)
- [ ] Design a optional graphical layout of weight and height development over time. 
- [ ] Find a comfortable way to switch between foot/inches and m/cm

**Comment by codingfabi** [comment]
Dumb question, but what system should we use for the height? foot and inches? or cm?

**Comment by codingfabi** [comment]
started implementing in branch HealthCheckFeature

**Comment by sleidig** [comment]
> Dumb question, but what system should we use for the height? foot and inches? or cm?

Not a dumb question at all. I think they would mostly use feet and inches in India. Let's start with that. But if you have any idea on how to make configurable, that's great

**Comment by codingfabi** [comment]
Idea: With the table, implement an option to show the measurements in a graph over time, so you can track the childs growth visually.
we should search a good library to do that.

**Comment by TheSlimvReal** [comment]
For displaying we could use a pipe that formats the weight/height into the correct format. One library I found for [metric pipes](https://github.com/vimalavinisha/angular2-metric-conversion-pipes) looks like it offers most of the functionality but I didn't test how well it works.

**Comment by sleidig** [comment]
A pipe to just adapt the displaying sounds like a great way to go. That will give us flexibility for more localization in the future, also. I would suggest we write metric units into the entities/database and modify the view as needed (for now, switching between feet/inches and meters should be enough).

**Comment by TheSlimvReal** [comment]
We should then define one type how we store it in the DB that will never change and only use the conversions in the displaying and reading of data. A problem might be how the user defines the unit (e.g. how do we know that the user enters a length in meters and not in feet). So we should propably create some components that let you select a metric unit and enter the value in a input field. Internaly we can use these two informations to determine the correct conversion.

**Comment by sleidig** [comment]
The basic feature is functional and merged with PR #224. The other points mentioned above remain. Maybe we should create separate issues for those?

**Comment by codingfabi** [comment]
I'll close this issue to keep the issues organized. The main features are implemented with pr#224. the open points will be put into a seperat issue with low priority.
